### PR TITLE
Add 'splunk_index' template variable

### PR DESCRIPTION
**Pull request by kwessel**

### CODE REVIEW

**Review by JonRoma — COMMENTED** [review]
@kwessel, finally reviewed this.

I've added a couple commits to this. The first commit, 85c8c6c75a129f0887280abeda85273de0846730, corrects a spelling error in your original commit, and shortens an over-long commit title. In reformatting, I'm using recommended style documented in [Commit message guidelines
](https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53). This commit is empty (i.e., it consists only of the updated commit message).

My second commit, 8464a34ed34fa30dd442893a3923b10a72959e74, made a minor wording change in the `README.md` documentation. I then realized that the Splunk usage justified adding an example to the documentation, and I did so – also correcting some typos and awkward language.

If you are happy with these changes, I'm not particular about whether you or I reorganize and squash the commits.

**Comment by JonRoma** [comment]
@kwessel, as an aside, I wonder if our Splunk-related SSM variable ought to be changed to something like `/service/foobar/splunk/hec_token`. It dawned on me that we will presumably tear down our CloudWatch logs.

The Splunk-specific SSM variables are currently defined in that module when the cloudwatch_to_splunk lambda function is enabled. They should probably be divorced from one another with the change to  remove CloudWatch from the data flow.

**Comment by kwessel** [comment]
I totally agree with that suggestion, Jon. I'd also befine with it being the service owner/deployer's job to declare that SSM variable. That way, it can just be in the ssm/terragrunt.hcl for the service. No need to auto-create it such that it's cluttering things up if it's not being used.

I, of course, can't say that all services using the ecs-service module will stop using Cloudwatch or the Lambda function. I can just speak for myself. It'd, of course, be nice if all of the IAMU services (Authman included) followed suit for consistency, but it's not a requirement. So, for now, no need to consider not continuing to create the specific /cloudwatch-to-splunk SSM vars. Whether you remove that from the ecs-service module and create them going forward in some other way is your call, though. I have no opinion there.

**Comment by kwessel** [comment]
> If you are happy with these changes, I'm not particular about whether you or I reorganize and squash the commits.

This all looks sane to me. I'll let you squash and merge them in. When it comes to the modules, I prefer to let you be the one to managethe merging, and not me, though I appreciate you giving me that option. I don't feel as strongly about making it all you for the actual infrastructure repos.

**Comment by JonRoma** [comment]
> > If you are happy with these changes, I'm not particular about whether you or I reorganize and squash the commits.
> 
> This all looks sane to me. I'll let you squash and merge them in. When it comes to the modules, I prefer to let you be the one to managethe merging, and not me, though I appreciate you giving me that option. I don't feel as strongly about making it all you for the actual infrastructure repos.

I agree with you there. As the primary infrastructure developer, it feels right for me to be the primary integrator of infrastructure commits. Likewise, your team is the primary integrator of application changes, so it makes sense for me to *not* be as actively involved in the integration of application code.

I'll take care of this one; thanks.

**Review by JonRoma — APPROVED** [review]

**Comment by JonRoma** [comment]
@kwessel, this has been merged and given the tag `v3.4.1`.

**Pull request merged**
